# Generated by Django 2.1 on 2018-09-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_name', models.CharField(max_length=264, unique=True)),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=264)),
                ('title', models.CharField(max_length=264)),
                ('eligibility', models.CharField(max_length=264)),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
    ]
