# Generated by Django 2.1 on 2018-09-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blrjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=264)),
                ('title', models.CharField(max_length=264)),
                ('eligibility', models.CharField(max_length=264)),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Chennaijobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=264)),
                ('title', models.CharField(max_length=264)),
                ('eligibility', models.CharField(max_length=264)),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Hydjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=264)),
                ('title', models.CharField(max_length=264)),
                ('eligibility', models.CharField(max_length=264)),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Punejobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=264)),
                ('title', models.CharField(max_length=264)),
                ('eligibility', models.CharField(max_length=264)),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
